---
Parameters:
  PythonPackage:
    Type: String
    Description: Enter the name of the Python package to be installed (uses pip3).
    Default: openai
  InstanceName:
    Type: String
    Description: Enter the name of your instance.
    Default: LinuxLambdaLayerCloudFormation


Resources:
  # EC2 Instance
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d0175e9dbb94e0d2 # Static AMI ID chosen from List of AMIs in the console
      InstanceType: t2.micro
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroups:
        - !Ref SSHSecurityGroup
      # Install Python, openai and Publish Lambda Layer
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash 
            sudo amazon-linux-extras install python3.9
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.9 get-pip.py --user
            mkdir -p home/ec2-user/python
            cd home/ec2-user
            python3.9 -m pip install ${PythonPackage} -t python/
            zip -r layer.zip python
            aws lambda publish-layer-version --layer-name ${PythonPackage}-layer --zip-file fileb://layer.zip --compatible-runtimes python3.10 --region ap-southeast-2
      Tags:
        - Key: Name
          Value: !Ref InstanceName

  # Instance Profile
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Join ["_", [!Ref InstanceName, "Profile"]]
      Path: /
      Roles:
        - !Ref InstanceRole

  # Instance Role
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["_", [!Ref InstanceName, "EC2PublishLambdaLayer"]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Join ["_", [!Ref InstanceName, "Policy"]]
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "lambda:PublishLayerVersion"
                Resource: "*"

  # EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and HTTP
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80